"use strict";

const COLLECTIONS = Object.freeze({
  accounts: "accounts",
  profiles: "profiles",
  medications: "medications",
  plans: "plans",
  snapshots: "snapshots",
  intakeLogs: "intake_logs",
  settings: "settings",
  calendarExports: "calendar_exports",
  idempotency: "idempotency",
  reminderTasks: "reminder_tasks",
  media: "media",
  deletionJobs: "deletion_jobs",
  subscriptionGrants: "subscription_grants",
  maintenanceCheckpoints: "maintenance_checkpoints",
  maintenanceJobs: "maintenance_jobs",
});

const PRIVACY_VERSION = "2026-09-07";

const DEFAULT_SETTINGS = Object.freeze({
  timezone: "Asia/Shanghai",
  privacyAcceptedVersion: null,
  privacyAcceptedAt: null,
  expiryLeadDays: 30,
  shortageLeadDays: 7,
  privateCalendarTitle: true,
  notificationPrivacy: "generic",
  subscriptions: Object.freeze({ expiry: false, shortage: false }),
  reminderPreferences: Object.freeze({
    dose: false,
    expiry: false,
    shortage: false,
  }),
});

const MUTATING_ACTIONS = new Set([
  "profile.create",
  "profile.update",
  "profile.delete",
  "medication.create",
  "medication.update",
  "medication.archive",
  "medication.delete",
  "plan.save",
  "plan.stop",
  "snapshot.create",
  "intake.record",
  "intake.undo",
  "settings.update",
  "account.delete",
  "acceptPrivacy",
  "upsertProfile",
  "archiveProfile",
  "saveMedication",
  "saveMedicationFast",
  "archiveMedication",
  "restoreMedication",
  "deleteMedication",
  "uploadMedicationPhoto",
  "putMedicationPhotoChunk",
  "finishMedicationPhotoUpload",
  "completeMedicationPhotoUpload",
  "processMedicationPhoto",
  "prepareMedicationPhoto",
  "commitMedicationPhoto",
  "removeMedicationPhoto",
  "discardMedicationPhoto",
  "recordSubscriptionGrant",
  "updateReminderSettings",
  "confirmInventory",
  "recordIntake",
  "recordIntakeQueued",
  "undoIntake",
  "saveCalendarExport",
  "updateSettings",
  "deleteAccount",
]);

const COMPAT_ACTIONS = new Set([
  "getTodayDashboard",
  "bootstrap",
  "acceptPrivacy",
  "upsertProfile",
  "archiveProfile",
  "saveMedication",
  "saveMedicationFast",
  "archiveMedication",
  "restoreMedication",
  "deleteMedication",
  "uploadMedicationPhoto",
  "putMedicationPhotoChunk",
  "finishMedicationPhotoUpload",
  "completeMedicationPhotoUpload",
  "processMedicationPhoto",
  "prepareMedicationPhoto",
  "commitMedicationPhoto",
  "removeMedicationPhoto",
  "discardMedicationPhoto",
  "getMedicationPhotoStatus",
  "recordSubscriptionGrant",
  "getReminderStatus",
  "updateReminderSettings",
  "confirmInventory",
  "recordIntake",
  "recordIntakeQueued",
  "undoIntake",
  "saveCalendarExport",
  "updateSettings",
  "exportData",
  "deleteAccount",
]);

const ACTIONS = new Set([
  "bootstrap",
  "today.get",
  "cabinet.get",
  "profile.list",
  "profile.create",
  "profile.update",
  "profile.delete",
  "medication.get",
  "medication.create",
  "medication.update",
  "medication.archive",
  "medication.delete",
  "plan.list",
  "plan.save",
  "plan.stop",
  "snapshot.list",
  "snapshot.create",
  "intake.list",
  "intake.record",
  "intake.undo",
  "settings.get",
  "settings.update",
  "data.export",
  "account.delete",
  ...COMPAT_ACTIONS,
]);

module.exports = {
  ACTIONS,
  COLLECTIONS,
  COMPAT_ACTIONS,
  DEFAULT_SETTINGS,
  MUTATING_ACTIONS,
  PRIVACY_VERSION,
};
