// Generated by scripts/build-shared-domain.mjs. Edit miniprogram/core/dashboard.ts.
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// miniprogram/core/dashboard.ts
var dashboard_exports = {};
__export(dashboard_exports, {
  buildRisks: () => buildRisks,
  buildTodayDashboard: () => buildTodayDashboard,
  buildTodayTasks: () => buildTodayTasks
});
module.exports = __toCommonJS(dashboard_exports);

// miniprogram/config/runtime.ts
var RUNTIME_CONFIG = {
  appName: "\u836F\u5C0F\u4F34",
  // Production builds must use the CloudBase environment bound to the official AppID.
  // Local storage is reserved for explicit demo builds only.
  deploymentMode: "demo",
  cloudEnvId: "",
  privacyVersion: "2026-09-07",
  timezone: "Asia/Shanghai",
  timezoneOffsetMinutes: 480,
  calendarHorizonDays: 90,
  defaultExpiryLeadDays: 30,
  defaultLowStockLeadDays: 7,
  subscriptionTemplates: {
    dose: "",
    expiry: "",
    lowStock: ""
  }
};

// miniprogram/core/dates.ts
var OFFSET_MS = RUNTIME_CONFIG.timezoneOffsetMinutes * 6e4;
var DATE_PATTERN = /^(\d{4})-(\d{2})-(\d{2})$/;
var MONTH_PATTERN = /^(\d{4})-(\d{2})$/;
var TIME_PATTERN = /^([01]\d|2[0-3]):([0-5]\d)$/;
var parts = (date) => {
  const match = DATE_PATTERN.exec(date);
  if (!match) throw new Error(`Invalid local date: ${date}`);
  return [Number(match[1]), Number(match[2]), Number(match[3])];
};
var isValidDateKey = (date) => {
  const match = DATE_PATTERN.exec(date);
  if (!match) return false;
  const year = Number(match[1]);
  const month = Number(match[2]);
  const day = Number(match[3]);
  const candidate = new Date(Date.UTC(year, month - 1, day));
  return candidate.getUTCFullYear() === year && candidate.getUTCMonth() === month - 1 && candidate.getUTCDate() === day;
};
var isValidMonthKey = (monthKey) => {
  const match = MONTH_PATTERN.exec(monthKey);
  if (!match) return false;
  const month = Number(match[2]);
  return month >= 1 && month <= 12;
};
var localDateTimeToMs = (date, time = "00:00") => {
  const [year, month, day] = parts(date);
  const timeMatch = TIME_PATTERN.exec(time);
  if (!timeMatch) throw new Error(`Invalid local time: ${time}`);
  return Date.UTC(year, month - 1, day, Number(timeMatch[1]), Number(timeMatch[2])) - OFFSET_MS;
};
var localDateTimeToIso = (date, time = "00:00") => new Date(localDateTimeToMs(date, time)).toISOString();
var dateKeyFromMs = (timestampMs) => new Date(timestampMs + OFFSET_MS).toISOString().slice(0, 10);
var todayKey = (nowMs = Date.now()) => dateKeyFromMs(nowMs);
var addDays = (date, amount) => {
  const [year, month, day] = parts(date);
  return new Date(Date.UTC(year, month - 1, day + amount)).toISOString().slice(0, 10);
};
var daysBetween = (fromDate, toDate) => {
  const [fy, fm, fd] = parts(fromDate);
  const [ty, tm, td] = parts(toDate);
  return Math.floor(
    (Date.UTC(ty, tm - 1, td) - Date.UTC(fy, fm - 1, fd)) / 864e5
  );
};
var endOfMonth = (monthKey) => {
  if (!isValidMonthKey(monthKey)) throw new Error(`Invalid month: ${monthKey}`);
  const [yearText, monthText] = monthKey.split("-");
  const year = Number(yearText);
  const month = Number(monthText);
  const day = new Date(Date.UTC(year, month, 0)).getUTCDate();
  return `${monthKey}-${String(day).padStart(2, "0")}`;
};
var dayOfWeek = (date) => {
  const [year, month, day] = parts(date);
  const sundayBased = new Date(Date.UTC(year, month - 1, day)).getUTCDay();
  return sundayBased === 0 ? 7 : sundayBased;
};
var startOfLocalDayMs = (timestampMs) => localDateTimeToMs(dateKeyFromMs(timestampMs), "00:00");
var endOfLocalDayMs = (timestampMs) => localDateTimeToMs(addDays(dateKeyFromMs(timestampMs), 1), "00:00") - 1;
var formatChineseDate = (date, precision = "day") => {
  if (precision === "month") {
    const [year2, month2] = date.split("-");
    return `${year2}\u5E74${Number(month2)}\u6708`;
  }
  const [year, month, day] = date.split("-");
  return `${year}\u5E74${Number(month)}\u6708${Number(day)}\u65E5`;
};
var formatShortChineseDate = (date) => {
  const [, month, day] = date.split("-");
  return `${Number(month)}\u6708${Number(day)}\u65E5`;
};

// miniprogram/core/expiry.ts
var calculateEffectiveExpiry = (input) => {
  const packageValid = input.expiryPrecision === "month" ? isValidMonthKey(input.expiryValue) : isValidDateKey(input.expiryValue);
  if (!packageValid) return null;
  const packageExpiryDate = input.expiryPrecision === "month" ? endOfMonth(input.expiryValue) : input.expiryValue;
  if (!input.openedDate || !isValidDateKey(input.openedDate) || !Number.isInteger(input.afterOpenDays) || (input.afterOpenDays ?? 0) < 1) {
    return {
      packageExpiryDate,
      openedExpiryDate: null,
      effectiveExpiryDate: packageExpiryDate,
      source: "package"
    };
  }
  const openedExpiryDate = addDays(
    input.openedDate,
    (input.afterOpenDays ?? 1) - 1
  );
  const openingWins = openedExpiryDate < packageExpiryDate;
  return {
    packageExpiryDate,
    openedExpiryDate,
    effectiveExpiryDate: openingWins ? openedExpiryDate : packageExpiryDate,
    source: openingWins ? "after-open" : "package"
  };
};
var resolveExpiry = (medication) => {
  const result = calculateEffectiveExpiry(medication);
  if (!result) throw new Error("Medication has an invalid package expiry");
  return result;
};
var effectiveExpiryDate = (medication) => resolveExpiry(medication).effectiveExpiryDate;
var daysUntilExpiry = (medication, nowMs = Date.now()) => daysBetween(todayKey(nowMs), effectiveExpiryDate(medication));

// miniprogram/core/schedule.ts
var isPlanActiveAt = (plan, scheduledAtMs, date) => {
  if (date < plan.startDate) return false;
  if (plan.endDate && date > plan.endDate) return false;
  if (scheduledAtMs < Date.parse(plan.effectiveFrom)) return false;
  if (plan.effectiveTo && scheduledAtMs >= Date.parse(plan.effectiveTo))
    return false;
  return true;
};
var appliesOnDate = (plan, date) => {
  if (plan.scheduleType === "daily") return true;
  if (plan.scheduleType === "weekly")
    return plan.weekdays.includes(dayOfWeek(date));
  return false;
};
var occurrenceKey = (planId, date, time) => `${planId}|${date}|${time}`;
var expandOccurrences = (plans, fromMs, toMs, medicationId) => {
  if (toMs < fromMs) return [];
  const occurrences = [];
  const startDate = dateKeyFromMs(fromMs);
  const endDate = dateKeyFromMs(toMs);
  for (const plan of plans) {
    if (medicationId && plan.medicationId !== medicationId) continue;
    if (plan.scheduleType === "as_needed") continue;
    let date = startDate;
    while (date <= endDate) {
      if (appliesOnDate(plan, date)) {
        for (const time of plan.times) {
          const scheduledAtMs = localDateTimeToMs(date, time);
          if (scheduledAtMs >= fromMs && scheduledAtMs <= toMs && isPlanActiveAt(plan, scheduledAtMs, date)) {
            occurrences.push({
              key: occurrenceKey(plan.id, date, time),
              medicationId: plan.medicationId,
              planId: plan.id,
              scheduledAt: localDateTimeToIso(date, time),
              scheduledAtMs,
              localDate: date,
              time,
              doseMilli: plan.doseMilli
            });
          }
        }
      }
      date = addDays(date, 1);
    }
  }
  return occurrences.sort(
    (a, b) => a.scheduledAtMs - b.scheduledAtMs || a.key.localeCompare(b.key)
  );
};
var occurrencesForLocalDay = (plans, nowMs, medicationId) => expandOccurrences(
  plans,
  startOfLocalDayMs(nowMs),
  endOfLocalDayMs(nowMs),
  medicationId
);

// miniprogram/core/inventory.ts
var latestSnapshot = (snapshots, medicationId, asOfMs) => snapshots.filter(
  (item) => item.medicationId === medicationId && Date.parse(item.recordedAt) <= asOfMs
).sort((a, b) => Date.parse(b.recordedAt) - Date.parse(a.recordedAt))[0] ?? null;
var activeLogs = (logs, medicationId, fromMs, toMs) => logs.filter((log) => {
  const occurredAt = Date.parse(log.occurredAt);
  return log.medicationId === medicationId && !log.voidedAt && occurredAt > fromMs && occurredAt <= toMs;
});
var estimateInventory = (args) => {
  const { medicationId, plans, snapshots, logs, asOfMs } = args;
  const snapshot = latestSnapshot(snapshots, medicationId, asOfMs);
  if (!snapshot) {
    return {
      medicationId,
      asOf: new Date(asOfMs).toISOString(),
      snapshotAt: null,
      currentQuantityMilli: null,
      lastCoveredAt: null,
      firstShortageAt: null,
      predictable: false,
      reason: "no-snapshot"
    };
  }
  const relevantPlans = plans.filter(
    (plan) => plan.medicationId === medicationId
  );
  const asOfDate = todayKey(asOfMs);
  const hasAsNeeded = relevantPlans.some(
    (plan) => plan.scheduleType === "as_needed" && plan.startDate <= asOfDate && (!plan.endDate || plan.endDate >= asOfDate) && Date.parse(plan.effectiveFrom) <= asOfMs && (!plan.effectiveTo || Date.parse(plan.effectiveTo) > asOfMs)
  );
  const logsSinceSnapshot = activeLogs(
    logs,
    medicationId,
    Date.parse(snapshot.recordedAt),
    asOfMs
  );
  const scheduled = expandOccurrences(
    relevantPlans,
    Date.parse(snapshot.recordedAt) + 1,
    asOfMs,
    medicationId
  ).filter(
    (occurrence) => !args.stopAtDate || occurrence.localDate <= args.stopAtDate
  );
  const scheduledByKey = new Map(
    scheduled.map((occurrence) => [occurrence.key, occurrence])
  );
  let loggedAdjustment = 0;
  for (const log of logsSinceSnapshot) {
    if (log.status === "extra") {
      loggedAdjustment += log.quantityMilli;
      continue;
    }
    const planned = log.occurrenceKey ? scheduledByKey.get(log.occurrenceKey) : void 0;
    if (log.status === "skipped" && planned) {
      loggedAdjustment -= planned.doseMilli;
    } else if (log.status === "taken" && !planned) {
      loggedAdjustment += log.quantityMilli;
    }
  }
  const scheduledConsumption = scheduled.reduce(
    (sum, item) => sum + item.doseMilli,
    0
  );
  const currentQuantityMilli = Math.max(
    0,
    snapshot.quantityMilli - scheduledConsumption - loggedAdjustment
  );
  if (hasAsNeeded) {
    return {
      medicationId,
      asOf: new Date(asOfMs).toISOString(),
      snapshotAt: snapshot.recordedAt,
      currentQuantityMilli,
      lastCoveredAt: null,
      firstShortageAt: null,
      predictable: false,
      reason: "as-needed"
    };
  }
  if (!relevantPlans.length) {
    return {
      medicationId,
      asOf: new Date(asOfMs).toISOString(),
      snapshotAt: snapshot.recordedAt,
      currentQuantityMilli,
      lastCoveredAt: null,
      firstShortageAt: null,
      predictable: false,
      reason: "no-plan"
    };
  }
  const forecastDays = args.forecastDays ?? 3650;
  const toDate = addDays(dateKeyFromMs(asOfMs), forecastDays);
  const forecastEndDate = args.stopAtDate && args.stopAtDate < toDate ? args.stopAtDate : toDate;
  const future = expandOccurrences(
    relevantPlans,
    asOfMs + 1,
    localDateTimeToMs(forecastEndDate, "23:59"),
    medicationId
  );
  let remaining = currentQuantityMilli;
  let lastCoveredAt = null;
  for (const occurrence of future) {
    if (remaining < occurrence.doseMilli) {
      return {
        medicationId,
        asOf: new Date(asOfMs).toISOString(),
        snapshotAt: snapshot.recordedAt,
        currentQuantityMilli,
        lastCoveredAt,
        firstShortageAt: occurrence.scheduledAt,
        predictable: true,
        reason: "ok"
      };
    }
    remaining -= occurrence.doseMilli;
    lastCoveredAt = occurrence.scheduledAt;
  }
  return {
    medicationId,
    asOf: new Date(asOfMs).toISOString(),
    snapshotAt: snapshot.recordedAt,
    currentQuantityMilli,
    lastCoveredAt,
    firstShortageAt: null,
    predictable: true,
    reason: "plan-ended"
  };
};

// miniprogram/core/dashboard.ts
var buildTodayTasks = (state, nowMs = Date.now()) => {
  const activeMedicationIds = new Set(
    state.medications.filter((item) => !item.archivedAt).map((item) => item.id)
  );
  const occurrences = occurrencesForLocalDay(
    state.plans.filter((plan) => activeMedicationIds.has(plan.medicationId)),
    nowMs
  );
  const logByOccurrence = new Map(
    state.intakeLogs.filter((log) => log.occurrenceKey && !log.voidedAt).map((log) => [log.occurrenceKey, log])
  );
  return occurrences.flatMap((occurrence) => {
    const medication = state.medications.find(
      (item) => item.id === occurrence.medicationId
    );
    if (!medication) return [];
    const profile = state.profiles.find(
      (item) => item.id === medication.profileId
    );
    if (!profile || profile.archivedAt) return [];
    const log = logByOccurrence.get(occurrence.key);
    let status;
    if ((log == null ? void 0 : log.status) === "taken") status = "taken";
    else if ((log == null ? void 0 : log.status) === "skipped") status = "skipped";
    else if (daysUntilExpiry(medication, nowMs) < 0) status = "needs-review";
    else status = occurrence.scheduledAtMs <= nowMs ? "due" : "upcoming";
    return [
      {
        ...occurrence,
        medicationName: medication.name,
        profileName: profile.name,
        profileColor: profile.color,
        unit: medication.unit,
        status,
        logId: (log == null ? void 0 : log.id) ?? null
      }
    ];
  });
};
var buildRisks = (state, nowMs = Date.now()) => {
  const today = todayKey(nowMs);
  const risks = [];
  for (const medication of state.medications.filter(
    (item) => !item.archivedAt
  )) {
    const expiry = resolveExpiry(medication);
    const expiryDate = expiry.effectiveExpiryDate;
    const remainingDays = daysBetween(today, expiryDate);
    if (remainingDays < 0) {
      risks.push({
        id: `expired-${medication.id}`,
        medicationId: medication.id,
        level: "danger",
        type: "expired",
        title: `${medication.name} \u5DF2\u8D85\u8FC7\u7BA1\u7406\u671F\u9650`,
        detail: expiry.source === "after-open" ? `\u5F00\u5C01\u540E\u671F\u9650\u5DF2\u4E8E${formatChineseDate(expiryDate)}\u7ED3\u675F\uFF0C\u8BF7\u6838\u5BF9\u6216\u79FB\u9664\u8FD9\u76D2\u836F` : `\u5305\u88C5\u6807\u6CE8${formatChineseDate(medication.expiryValue, medication.expiryPrecision)}\uFF0C\u8BF7\u6838\u5BF9\u6216\u79FB\u9664\u8FD9\u76D2\u836F`
      });
    } else if (remainingDays <= state.settings.expiryLeadDays) {
      const relativeText = remainingDays === 0 ? "\u4ECA\u5929\u5230\u671F" : remainingDays === 1 ? "\u660E\u5929\u5230\u671F" : `\u8FD8\u5269${remainingDays}\u5929`;
      risks.push({
        id: `expiring-${medication.id}`,
        medicationId: medication.id,
        level: "warning",
        type: "expiring",
        title: remainingDays === 0 ? `${medication.name} \u4ECA\u5929\u5230\u671F` : `${medication.name} \u5373\u5C06\u5230\u671F`,
        detail: `${formatShortChineseDate(expiryDate)}\u7BA1\u7406\u5230\u671F\uFF0C${relativeText}${expiry.source === "after-open" ? "\uFF08\u6309\u5F00\u5C01\u540E\u671F\u9650\uFF09" : ""}`
      });
    }
    if (remainingDays >= 0) {
      const estimate = estimateInventory({
        medicationId: medication.id,
        plans: state.plans,
        snapshots: state.snapshots,
        logs: state.intakeLogs,
        asOfMs: nowMs,
        stopAtDate: expiryDate
      });
      if (estimate.currentQuantityMilli === 0 && estimate.snapshotAt) {
        risks.push({
          id: `low-stock-${medication.id}`,
          medicationId: medication.id,
          level: "warning",
          type: "low-stock",
          title: `${medication.name} \u9884\u8BA1\u4F59\u91CF\u4E3A 0`,
          detail: "\u8BF7\u76D8\u70B9\u786E\u8BA4\uFF1B\u5982\u679C\u5DF2\u7ECF\u7528\u5B8C\uFF0C\u53EF\u4EE5\u79FB\u9664\u8FD9\u76D2\u836F"
        });
      } else if (estimate.firstShortageAt) {
        const shortageDate = todayKey(Date.parse(estimate.firstShortageAt));
        const shortageDays = daysBetween(today, shortageDate);
        if (shortageDays <= state.settings.lowStockLeadDays) {
          risks.push({
            id: `low-stock-${medication.id}`,
            medicationId: medication.id,
            level: "warning",
            type: "low-stock",
            title: `${medication.name} \u9884\u8BA1\u4F59\u91CF\u4E0D\u8DB3`,
            detail: `\u6309\u8BA1\u5212\u4F30\u7B97\uFF0C${formatShortChineseDate(shortageDate)}\u8D77\u53EF\u80FD\u4E0D\u8DB3\uFF0C\u8BF7\u5148\u76D8\u70B9`
          });
        }
      } else if (medication.mode !== "expiry_only" && !estimate.snapshotAt) {
        risks.push({
          id: `unknown-stock-${medication.id}`,
          medicationId: medication.id,
          level: "info",
          type: "unknown-stock",
          title: `${medication.name} \u5C1A\u672A\u76D8\u70B9`,
          detail: "\u586B\u5199\u73B0\u6709\u6570\u91CF\u540E\uFF0C\u53EF\u4F30\u7B97\u4EC0\u4E48\u65F6\u5019\u7528\u5B8C"
        });
      }
    }
    const activePlan = state.plans.find(
      (item) => item.medicationId === medication.id && item.effectiveTo === null
    );
    const hasCurrentCalendar = Boolean(
      activePlan && state.calendarExports.some(
        (item) => item.medicationId === medication.id && item.planId === activePlan.id && !item.staleAt
      )
    );
    const staleCalendar = !hasCurrentCalendar && state.calendarExports.some(
      (item) => item.medicationId === medication.id && item.staleAt
    );
    if (staleCalendar) {
      risks.push({
        id: `calendar-stale-${medication.id}`,
        medicationId: medication.id,
        level: "info",
        type: "calendar-stale",
        title: `${medication.name} \u6709\u65E7\u65E5\u5386\u63D0\u9192`,
        detail: "\u8BA1\u5212\u5DF2\u53D8\u5316\uFF0C\u8BF7\u5230\u624B\u673A\u7CFB\u7EDF\u65E5\u5386\u5220\u9664\u65E7\u4E8B\u4EF6"
      });
    }
  }
  const levelOrder = {
    danger: 0,
    warning: 1,
    info: 2
  };
  return risks.sort(
    (a, b) => levelOrder[a.level] - levelOrder[b.level] || a.title.localeCompare(b.title)
  );
};
var buildTodayDashboard = (state, nowMs = Date.now()) => {
  var _a;
  const tasks = buildTodayTasks(state, nowMs);
  const medications = state.medications.filter((item) => !item.archivedAt);
  const next = tasks.find((item) => ["upcoming", "due"].includes(item.status));
  return {
    syncScope: state.syncScope,
    privacyAcceptedVersion: state.settings.privacyAcceptedVersion,
    generatedAt: new Date(nowMs).toISOString(),
    tasks,
    risks: buildRisks(state, nowMs),
    summary: {
      medicationCount: medications.length,
      multipleProfiles: state.profiles.filter((item) => !item.archivedAt).length > 1,
      pendingCount: tasks.filter(
        (item) => ["upcoming", "due"].includes(item.status)
      ).length,
      recordedCount: tasks.filter(
        (item) => ["taken", "skipped"].includes(item.status)
      ).length,
      planlessMedicationId: ((_a = medications.find(
        (item) => item.mode !== "expiry_only" && !state.plans.some(
          (plan) => plan.medicationId === item.id && !plan.effectiveTo
        )
      )) == null ? void 0 : _a.id) ?? ""
    },
    nextReminder: next ? { scheduledAt: next.scheduledAt, medicationId: next.medicationId } : null
  };
};
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  buildRisks,
  buildTodayDashboard,
  buildTodayTasks
});
